#!/usr/bin/python3
'Program to rebind configured devices after resume from suspend.'
# Author: Mark Blakeney, Feb 2021.

import sys
import time
import argparse
from pathlib import Path

RETRIES = 30

def rebind(dev):
    'Rebind the specified device'
    if not dev.exists():
        return False, f'No device {dev}'

    name = dev.name
    unbind = dev.with_name('unbind')
    bind = dev.with_name('bind')

    # Keep trying until we get a successful bind ..
    for retry in range(1, RETRIES + 1):
        try:
            unbind.write_text(name)
        except Exception:
            pass

        try:
            bind.write_text(name)
        except Exception:
            pass
        else:
            s = 's' if retry > 1 else ''
            return True, f'Rebound {dev} in {retry} attempt{s}.'

        time.sleep(1)

    return False, f'Failed to rebind {dev} within {retry} attempts.'

# Process command line options
opt = argparse.ArgumentParser(description=__doc__.strip(),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
opt.add_argument('-c', '--config', default=f'/etc/{opt.prog}.conf',
        help='config file')
args = opt.parse_args()

conf = Path(args.config)
if not conf.exists():
    sys.exit(f'Configuration file {conf} does not exist.')

for line in conf.open():
    line = line.strip()
    if line and line[0] != '#':
        success, msg = rebind(Path(line))
        print(msg, file=(sys.stdout if success else sys.stderr))
